### ISSUE TITLE
Cannot register class [models.Token] in Ebean server

### ISSUE THREAD

**Issue by AidanDelaney** [yesnault/PlayStartApp#19]
Given a clean clone of this project and running with the latest activator, I get an associated with the Token.class in models.

```bash
$ ../activator-1.3.12-minimal/bin/activator run
[info] Loading project definition from /home/aidan/tmp/PlayStartApp/project
[info] Set current project to PlayStartApp (in build file:/home/aidan/tmp/PlayStartApp/)
[info] Updating {file:/home/aidan/tmp/PlayStartApp/}root...
[info] Resolving net.contentobjects.jnotify#jnotify;0.94-play-1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.play:play-jdbc_2.11:2.4.0 -> 2.5.0
[warn] 	* com.typesafe.play:play-java_2.11:2.4.0 -> 2.5.0
[warn] Run 'evicted' to see detailed eviction warnings

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 26 Scala sources and 17 Java sources to /home/aidan/tmp/PlayStartApp/target/scala-2.11/classes...
[info] /home/aidan/tmp/PlayStartApp/app/controllers/Application.java: Some input files use or override a deprecated API.
[info] /home/aidan/tmp/PlayStartApp/app/controllers/Application.java: Recompile with -Xlint:deprecation for details.
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:h2:mem:play
[error] application - 

! @7269n8i8j - Internal server error, for (GET) [/] ->
 
play.api.Configuration$$anon$1: Configuration error[Cannot register class [models.Token] in Ebean server]
	at play.api.Configuration$.configError(Configuration.scala:154)
	at play.api.Configuration.reportError(Configuration.scala:806)
	at play.Configuration.reportError(Configuration.java:366)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser.parse(DefaultEbeanConfig.java:105)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:60)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:44)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    models/Token.sendMail(Lmodels/User;Lmodels/Token$TypeToken;Ljava/lang/String;Lplay/libs/mailer/MailerClient;)V @155: invokevirtual
  Reason:
    Type 'models/User' (current frame, stack[0]) is not assignable to 'models/Token'
  Current Frame:
    bci: @155
    flags: { }
    locals: { 'models/Token', 'models/User', 'models/Token$TypeToken', 'java/lang/String', 'play/libs/mailer/MailerClient', 'models/Token', 'java/lang/String', 'java/lang/String', 'java/lang/String', null, 'java/lang/String', 'java/net/URL' }
    stack: { 'models/User' }
  Bytecode:
    0x0000000: 2a2b 2c2d b700 bd3a 05b8 00c3 12c5 b600
    0x0000010: c93a 0601 3a07 013a 0801 3a09 bb00 cb59
    0x0000020: b700 cc12 ceb6 00d2 1906 b600 d212 d4b6
    0x0000030: 00d2 2cb8 00d8 b600 d212 d4b6 00d2 1905
    0x0000040: b600 dbb6 00d2 b600 dc59 3a0a 3a0a bb00
    0x0000050: de59 190a b700 e03a 0bb2 00e4 2cb6 00e8
    0x0000060: 2eab 0000 0000 0067 0000 0002 0000 0001
    0x0000070: 0000 001b 0000 0002 0000 0042 12ea 03bd
    0x0000080: 00ec b800 f23a 0712 f404 bd00 ec59 0319
    0x0000090: 0bb6 00f5 53b8 00f2 3a08 2bb6 00f8 3a09
    0x00000a0: a700 2812 fa03 bd00 ecb8 00f2 3a07 12fc
    0x00000b0: 04bd 00ec 5903 190b b600 f553 b800 f23a
    0x00000c0: 0819 05b6 00f8 3a09 bb00 cb59 b700 cc12
    0x00000d0: feb6 00d2 190b b601 01b6 00dc b801 06bb
    0x00000e0: 001f 5919 0719 0819 09b7 0109 3a0c bb00
    0x00000f0: 2159 1904 b701 0c3a 0d19 0d19 0cb6 010f
    0x0000100: b1                                     
  Stackmap Table:
    full_frame(@124,{Object[#2],Object[#150],Object[#12],Object[#284],Object[#286],Object[#2],Object[#284],Null,Null,Null,Object[#284],Object[#222]},{})
    same_frame(@163)
    full_frame(@200,{Object[#2],Object[#150],Object[#12],Object[#284],Object[#286],Object[#2],Object[#284],Object[#284],Object[#284],Object[#284],Object[#284],Object[#222]},{})

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser.parse(DefaultEbeanConfig.java:103)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:60)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:44)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
```

**Comment by yesnault** [comment]
Hi. This project is not maintained anymore, feel free to open a PR to add compatibility with latest activator.
